// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	jarivsupd "hackathon/cmd/jarvis/internal/handler/jarivsupd"
	noderelease "hackathon/cmd/jarvis/internal/handler/noderelease"
	"hackathon/cmd/jarvis/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/jarvisconf",
				Handler: jarivsupd.GetJarvisUpdConfHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/jarvisconf/:nodeId",
				Handler: jarivsupd.GetNodeJarvisUpdConfHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/v1/jarvisconf",
				Handler: jarivsupd.UpdateJarvisUpdConfHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/v1/allow_nodes",
				Handler: jarivsupd.UpdateAllowNodesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/allow_nodes",
				Handler: jarivsupd.GetAllowNodesHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/create",
				Handler: noderelease.NodeReleaseCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/:releaseID/continue",
				Handler: noderelease.NodeReleaseContinueHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/:releaseID/rollback",
				Handler: noderelease.NodeReleaseRollbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/:releaseID/complete",
				Handler: noderelease.NodeReleaseCompleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/:releaseID/filterswitch",
				Handler: noderelease.NodeReleaseFilterSwitchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/list",
				Handler: noderelease.NodeReleaseListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/release/:releaseID/detail",
				Handler: noderelease.NodeReleaseDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/release/:releaseID/allownodes/export",
				Handler: noderelease.NodeReleaseAllowNodesExportHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/release/:releaseID/history",
				Handler: noderelease.NodeReleaseHistoryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/packages",
				Handler: noderelease.NodeReleasePackagesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/release/allowapps",
				Handler: noderelease.NodeReleaseAllowAppsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/release/allowapps",
				Handler: noderelease.NodeReleaseAllowAppsUpdateHandler(serverCtx),
			},
		},
	)
}
